version: "3.8"

services:
  grocy:
    image: zebradil/beehive
    deploy:
      labels:
        - "traefik.backend=beehive"
        - "traefik.frontend.rule=Host:beehive.${DOMAIN:?}"
        - "traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-public"
        - "traefik.backend.loadbalancer.method=drr"
        - "traefik.frontend.auth.basic.users=${ADMIN_USER}:${HASHED_PASSWORD}"
      restart_policy:
        condition: on-failure
    environment:
      - 'CANONICAL_URL=0.0.0.0:8181'
      - PGID=1000
      - TZ=Europe/Berlin
      - GROCY_CULTURE=ru
    volumes:
      - beehive_config:/conf
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: traefik-public

volumes:
  beehive_config:

