version: '3.8'

networks:
  proxy:
    name: "${NET_NAME:?}"
    external: true

volumes:
  data:

services:
  taskd:
    image: zebradil/taskd
    networks:
      - proxy
    volumes:
      - data:/var/taskd
    environment:
      - "CERT_CN=taskd.${DOMAIN:?}"
      - "CERT_COUNTRY=${TASKD_COUNTRY:?}"
      - "CERT_LOCALITY=${TASKD_LOCALITY:?}"
      - "CERT_ORGANIZATION=${TASKD_ORGANIZATION:?}"
      - "CERT_STATE=${TASKD_STATE:?}"
    ports:
      - 53589:53589
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
