version: '3.7'

networks:
  proxy:
    name: "${NET_NAME:?}"
    external: true

volumes:
  data:

services:
  taskd:
    image: zebradil/taskd
    networks:
      - proxy
    volumes:
      - data:/var/taskd
    environment:
      - "CERT_CN=taskd.${DOMAIN:?}"
      - "CERT_COUNTRY=${TASKD_COUNTRY:?}"
      - "CERT_LOCALITY=${TASKD_LOCALITY:?}"
      - "CERT_ORGANIZATION=${TASKD_ORGANIZATION:?}"
      - "CERT_STATE=${TASKD_STATE:?}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        ## HTTP Routers
        - "traefik.tcp.routers.taskd-rtr.entrypoints=taskd"
        - "traefik.tcp.routers.taskd-rtr.rule=HostSNI(`taskd.${DOMAIN:?}`)"
        - "traefik.tcp.routers.taskd-rtr.tls=true"
        - "traefik.tcp.routers.taskd-rtr.tls.passthrough=true"
        ## HTTP Services
        - "traefik.tcp.routers.taskd-rtr.service=taskd-svc"
        - "traefik.tcp.services.taskd-svc.loadbalancer.server.port=53589"
