version: "3.7"

services:
  traefik:
    image: traefik:2.2
    command:
      - "--logLevel=WARNING"
      - "--docker.domain=${DOMAIN:?}"
      - "--acme.keytype=EC256"
      - "--acme.domains=*.${DOMAIN:?}"
      - "--acme.email=${ACME_EMAIL}"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      # TODO replace direct mount by using proxy
      # https://github.com/BretFisher/dogvscat/blob/master/stack-proxy-global.yml#L124
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/data/traefik/traefik.toml:/traefik.toml:ro"
      - "/var/data/traefik/.htpasswd:/.htpasswd:ro"
      - "/var/data/traefik/acme.json:/acme.json"
      - "/var/log/traefik:/logs"
    networks:
      - proxy
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host:traefik.${DOMAIN:?}"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}"
        - "traefik.docker.network=traefik-public"
    secrets:
      - cloudflare-api-key
      - cloudflare-api-mail
    environment:
      CF_API_KEY_FILE: /run/secrets/cloudflare-api-key
      CF_API_EMAIL_FILE: /run/secrets/cloudflare-api-mail

secrets:
  cloudflare-api-key:
    external: true
  cloudflare-api-mail:
    external: true

networks:
  proxy:
    name: traefik-public
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/24
