checkNewVersion = true
defaultEntryPoints = ["http", "https"]

# This section enable LetsEncrypt automatic certificate generation / renewal
[acme]
storage = "acme.json" # or "traefik/acme/account" if using KV store
entryPoint = "https"
acmeLogging = true
onHostRule = true
  [acme.dnsChallenge]
  provider = "cloudflare"

# Redirect all HTTP to HTTPS (why wouldn't you?)
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.api]
  address=":8080"
    [entryPoints.api.auth]
      [entryPoints.api.auth.basic]
        usersFile = "/.htpasswd"

[api]
entrypoint = "api"

[docker]
endpoint = "tcp://127.0.0.1:2375"
watch = true
swarmmode = true

[accessLog]
filePath = "/logs/access.log"
bufferingSize = 100
