http:
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: /.htpasswd
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
    oauth:
      forwardAuth:
        address: 'http://oauth:4181'
        trustForwardHeader: true
        authResponseHeaders:
          - X-Forwarded-User

    chain-no-auth:
      chain:
        middlewares:
          - rate-limit
    chain-basic-auth:
      chain:
        middlewares:
          - rate-limit
          - basic-auth
    chain-oauth:
      chain:
        middlewares:
          - rate-limit
          - oauth

tls:
  options:
    intermediate:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
