version: '3.7'

networks:
  proxy:
    name: "${NET_NAME?:}"
    external: true
  internal:

services:
  web:
    image: registry.gitlab.com/commento/commento
    networks:
      - proxy
      - internal
    environment:
      - "COMMENTO_ORIGIN=https://commento.${DOMAIN:?}"
      - "COMMENTO_PORT=80"
      - "COMMENTO_POSTGRES=postgres://postgres:postgres@db:5432/commento?sslmode=disable"
      - "COMMENTO_FORBID_NEW_OWNERS=true"
    env_file:
      - ".env"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        ## HTTP Routers
        - "traefik.http.routers.commento-rtr.entrypoints=https"
        - "traefik.http.routers.commento-rtr.rule=Host(`commento.${DOMAIN:?}`)"
        - "traefik.http.routers.commento-rtr.tls=true"
        - "traefik.http.routers.commento-rtr.tls.certresolver=dns-cloudflare"
        ## Middlewares
        - "traefik.http.routers.commento-rtr.middlewares=chain-no-auth@file"
        ## HTTP Services
        - "traefik.http.routers.commento-rtr.service=commento-svc"
        - "traefik.http.services.commento-svc.loadbalancer.server.port=80"

  db:
    image: postgres:11
    stop_signal: SIGTERM
    networks:
      - internal
    volumes:
      - "/var/data/commento/postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=commento"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
