version: "3.7"

networks:
  proxy:
    name: "${NET_NAME?:}"
    external: true

services:
  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/data/portainer/data:/data"
    environment:
      - "TZ=${TZ:?}"
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=true"
        ## HTTP Routers
        - "traefik.http.routers.portainer-rtr.entrypoints=https"
        - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.${DOMAIN:?}`)"
        - "traefik.http.routers.portainer-rtr.tls=true"
        - "traefik.http.routers.portainer-rtr.tls.certresolver=dns-cloudflare"
        ## Middlewares
        - "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file"
        ## HTTP Services
        - "traefik.http.routers.portainer-rtr.service=portainer-svc"
        - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
