version: "3.8"

networks:
  proxy:
    name: "${NET_NAME:?}"
    external: true

services:
  heimdall:
    image: linuxserver/heimdall:latest
    networks:
      - proxy
    volumes:
      - /var/data/heimdall:/config
    environment:
      - "TZ=${TZ:?}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        ## HTTP Routers
        - "traefik.http.routers.heimdall-rtr.entrypoints=https"
        - "traefik.http.routers.heimdall-rtr.rule=Host(`heimdall.${DOMAIN:?}`)"
        - "traefik.http.routers.heimdall-rtr.tls=true"
        - "traefik.http.routers.heimdall-rtr.tls.certresolver=dns-cloudflare"
        ## Middlewares
        - "traefik.http.routers.heimdall-rtr.middlewares=chain-oauth@file"
        ## HTTP Services
        - "traefik.http.routers.heimdall-rtr.service=heimdall-svc"
        - "traefik.http.services.heimdall-svc.loadbalancer.server.port=80"
