version: '3.7'

services:
  grocy:
    image: linuxserver/grocy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.router0.rule=Host(grocy.${DOMAIN:?})"
        - "traefik.backend=grocy"
        - "traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-public"
      restart_policy:
        condition: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - GROCY_CULTURE=ru
    volumes:
      - grocy_config:/config
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: traefik-public

volumes:
  grocy_config:

