---
version: "2"
services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - grocy_config:/config
    ports:
      - 9283:80
    restart: unless-stopped

volumes:
  grocy_config:
